# Generated by Django 3.2.25 on 2024-06-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vacancy',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=60)),
                ('url', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
            ],
        ),
    ]
