# Generated by Django 3.2.25 on 2024-07-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vacancy_grafi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='grafi',
            new_name='grafic',
        ),
    ]
