# Generated by Django 3.2.25 on 2024-07-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_grafi_vacancy_grafic'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
    ]
