# Generated by Django 3.2.25 on 2024-07-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_vacancy_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='requirement',
            field=models.CharField(default=2, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibility',
            field=models.CharField(default=2, max_length=400),
            preserve_default=False,
        ),
    ]
